import { copyFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import builtins from 'builtin-modules'
import esbuild from 'esbuild'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Repository: https://github.com/liulinlin/md
*/`

const prod = process.argv[2] === 'production'

// 开发模式：输出到 Obsidian 测试仓库的插件目录
const vaultPath = process.env.OBSIDIAN_VAULT_PATH
const pluginDir = vaultPath
  ? path.join(vaultPath, '.obsidian', 'plugins', 'wechat-publisher')
  : null

// Plugin to handle Vite-style ?raw imports (used by @md/shared)
const rawImportPlugin = {
  name: 'raw-import',
  setup(build) {
    build.onResolve({ filter: /\?raw$/ }, (args) => {
      const resolved = path.resolve(args.resolveDir, args.path.replace(/\?raw$/, ''))
      return { path: resolved }
    })
  },
}

// Node.js 内建模块 shim 插件
// postcss（@md/core 依赖）使用 fs/path/url 处理 source map，reading-time 使用 stream/util
// 这些功能在移动端 WebView 中不可用，提供 shim 使其降级运行
// reading-time 的 stream.js 在模块加载时调用 util.inherits 和 stream.Transform，
// 需要提供最小 polyfill 避免崩溃（stream 功能运行时不会被实际调用）
const nodeShimPlugin = {
  name: 'node-builtins-shim',
  setup(build) {
    const shimmed = new Set(builtins.flatMap(m => [m, `node:${m}`]))
    build.onResolve({ filter: /.*/ }, (args) => {
      if (shimmed.has(args.path)) {
        return { path: args.path, namespace: 'node-shim' }
      }
    })
    build.onLoad({ filter: /.*/, namespace: 'node-shim' }, (args) => {
      const mod = args.path.replace(/^node:/, '')
      // util: reading-time 的 stream.js 调用 util.inherits(ReadingTimeStream, Transform)
      if (mod === 'util') {
        return {
          contents: `module.exports = {
  inherits: function(ctor, superCtor) {
    if (superCtor) {
      ctor.super_ = superCtor;
      ctor.prototype = Object.create(superCtor.prototype, {
        constructor: { value: ctor, writable: true, configurable: true }
      });
    }
  }
};`,
          loader: 'js',
        }
      }
      // stream: reading-time 的 stream.js 需要 stream.Transform 构造函数
      if (mod === 'stream') {
        return {
          contents: `function Transform() {} module.exports = { Transform: Transform };`,
          loader: 'js',
        }
      }
      return { contents: 'module.exports = {};', loader: 'js' }
    })
  },
}

// 开发模式下构建完成后自动复制到测试仓库
const deployPlugin = {
  name: 'deploy-to-vault',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0 || !pluginDir)
        return
      await mkdir(pluginDir, { recursive: true })
      const src = path.dirname(fileURLToPath(import.meta.url))
      await copyFile(path.join(src, 'manifest.json'), path.join(pluginDir, 'manifest.json'))
      await copyFile(path.join(src, 'styles', 'styles.css'), path.join(pluginDir, 'styles.css'))
      // main.js 由 esbuild 直接输出到 pluginDir
      console.log(`Deployed to ${pluginDir}`)
    })
  },
}

const outfile = prod
  ? 'dist/main.js'
  : pluginDir
    ? path.join(pluginDir, 'main.js')
    : 'main.js'

const plugins = [rawImportPlugin, nodeShimPlugin]
if (!prod && pluginDir) {
  plugins.push(deployPlugin)
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  platform: 'browser',
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    'mermaid',
    '@antv/infographic',
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile,
  minify: prod,
  plugins,
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  loader: {
    '.css': 'text',
    '.txt': 'text',
  },
})

if (prod) {
  await context.rebuild()
  await context.dispose()

  await mkdir('dist', { recursive: true })
  await copyFile('manifest.json', 'dist/manifest.json')
  await copyFile('styles/styles.css', 'dist/styles.css')

  console.log('Build complete!')
}
else {
  await context.watch()
  console.log(`Watching for changes...${pluginDir ? ` (deploying to ${pluginDir})` : ''}`)
}
